# Generated by Django 3.2.8 on 2021-11-13 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('feedback_user', models.CharField(max_length=500)),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user_policy',
            name='policy_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
